name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    # secrets:
    #   token:
    #     required: true

jobs:
  example_job:
    name: Run Sub Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Do Build Things
        run: echo "Doing Build Things Here for environment > ${{ inputs.environment }}"
