name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Do Production Things
        if: env.SUPER_SECRET == 'Production Super Secret'
        run: echo "::set-env name=MESSAGE::'Production! Lets Go!'"

      - name: Do Staging Things
        if: env.SUPER_SECRET == 'Staging Super Secret'
        run: echo "::set-env name=MESSAGE::'Staging! Lets Go!'"

      - name: Print Message
        run: echo $MESSAGE
